name: Organize Gallery Photos
on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'content/gallery/**'
    branches-ignore:
      - main
jobs:
  organize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Run organize_gallery.py
        run: |
          pip install --upgrade pip
          python scripts/organize_gallery.py
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add content/gallery
          git commit -m 'Organize gallery photos and add index.md files' || echo 'No changes to commit'
          git push
